# Generated by Django 5.2.5 on 2025-12-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_table',
            name='rating',
        ),
    ]
