# Generated by Django 5.2.5 on 2025-12-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_feedback_table_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='emotion_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('emotion', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
