# Generated by Django 5.2.5 on 2025-12-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_emotion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion_table',
            name='patient_id',
            field=models.IntegerField(),
        ),
    ]
