# Generated by Django 5.2.5 on 2025-12-31 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_emotion_table_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion_table',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_table'),
        ),
    ]
